DELETE FROM COMMENTS;
DELETE FROM BOOKS_AUTHORS;
DELETE FROM BOOKS;
DELETE FROM GENRES;
DELETE FROM AUTHORS;

INSERT INTO AUTHORS (FIO) VALUES ('Pushkin');
INSERT INTO AUTHORS (FIO) VALUES ('Lermontov');
INSERT INTO AUTHORS (FIO) VALUES ('Gogol');

INSERT INTO GENRES (NAME) VALUES ('Povest');
INSERT INTO GENRES (NAME) VALUES ('Skazka');

INSERT INTO BOOKS (NAME, GENRE_ID) VALUES ('Book1Name', 1);
INSERT INTO BOOKS (NAME, GENRE_ID) VALUES ('Book2Name', 2);
INSERT INTO BOOKS (NAME, GENRE_ID) VALUES ('Book3Name', 1);

INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (1, 2);
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (2, 2);
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (3, 2);
INSERT INTO BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (3, 3);

INSERT INTO COMMENTS (TEXT, BOOK_ID) VALUES ('Super', 1);
INSERT INTO COMMENTS (TEXT, BOOK_ID) VALUES ('Kruto', 2);
INSERT INTO COMMENTS (TEXT, BOOK_ID) VALUES ('Nravitsa', 2);
INSERT INTO COMMENTS (TEXT, BOOK_ID) VALUES ('Otpad', 3);

