DELETE FROM BOOKS;
DELETE FROM AUTHORS;
DELETE FROM GENRES;

INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Pushkin');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Lermontov');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Tolstoj');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Gogol');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Groboedov');

INSERT INTO GENRES (GENRE_NAME) VALUES ('Povest');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Stihotvorenie');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Skazka');

INSERT INTO BOOKS (BOOK_NAME, AUTHOR_ID, GENRE_ID) VALUES ('Voina i mir', 1,1);
INSERT INTO BOOKS (BOOK_NAME, AUTHOR_ID, GENRE_ID) VALUES ('Nos', 2,2);
INSERT INTO BOOKS (BOOK_NAME, AUTHOR_ID, GENRE_ID) VALUES ('Ruslan i ludmila', 1,1);