DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;


CREATE TABLE IF NOT EXISTS BOOKS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  NAME		    VARCHAR(50),
  GENRE_ID		INT
);

CREATE TABLE IF NOT EXISTS BOOKS_AUTHORS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  BOOK_ID     INT,
  AUTHOR_ID   INT
);

CREATE TABLE  IF NOT EXISTS AUTHORS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  FIO		      VARCHAR(50)
);

CREATE TABLE  IF NOT EXISTS GENRES (
  ID    			INT PRIMARY KEY AUTO_INCREMENT,
  NAME		    VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS COMMENTS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  TEXT        VARCHAR(250),
  BOOK_ID     INT
);

ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID);
ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID);
ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID);
ALTER TABLE COMMENTS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID);