CREATE TABLE IF NOT EXISTS BOOKS (
	ID				  INT PRIMARY KEY AUTO_INCREMENT,
  BOOK_NAME		VARCHAR(50),
  AUTHOR_ID		INT,
  GENRE_ID		INT
);

CREATE TABLE  IF NOT EXISTS AUTHORS (
	ID				    INT PRIMARY KEY AUTO_INCREMENT,
  AUTHOR_NAME		VARCHAR(50)
);

CREATE TABLE  IF NOT EXISTS GENRES (
	ID    				INT PRIMARY KEY AUTO_INCREMENT,
  GENRE_NAME		VARCHAR(50)
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID);